# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

###########################
### Course service 9000 ###
###########################

GET http://127.0.0.1:9003/courses

###

GET http://127.0.0.1:9003/courses/1


############################
### Student Service 9001 ###
############################

GET http://127.0.0.1:9003/students/1

###

GET http://127.0.0.1:9003/students


##################################
### StudentCourse Service 9002 ###
##################################

GET http://127.0.0.1:9003/coursestudents/1

###